# Generated by Django 4.2 on 2025-01-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(default='', max_length=60, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(default='', max_length=20, verbose_name='Telefono'),
        ),
    ]
