# Generated by Django 3.2.7 on 2023-04-30 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFactura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('valor', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='MediosDePago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Medios de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('telefono', models.CharField(default='', max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('factura', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='Id de cliente')),
                ('detalle', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('observacion', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('precio', models.IntegerField(default=0)),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Venta')),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Venta')),
                ('estado', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabilidad.estadoventa', verbose_name='Id de cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PagosProveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('Estado', models.CharField(default='', max_length=50)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabilidad.proveedores', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Abonos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='Id de cliente')),
                ('precio', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('factura_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contabilidad.ventas', verbose_name='Id de cliente')),
                ('medioDePago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contabilidad.mediosdepago', verbose_name='Medio de Pago')),
            ],
        ),
    ]
