# Generated by Django 3.2.7 on 2023-04-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_auto_20230430_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='cliente_id',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Id de cliente'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='factura',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
