# Generated by Django 4.2 on 2025-01-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_auto_20230430_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonos',
            options={'managed': True, 'verbose_name': 'Abonos', 'verbose_name_plural': 'Abonos'},
        ),
        migrations.AlterModelOptions(
            name='estadoventa',
            options={'managed': True, 'verbose_name': 'Estado Venta', 'verbose_name_plural': 'Estado Venta'},
        ),
        migrations.AlterModelOptions(
            name='ventas',
            options={'managed': True, 'verbose_name': 'Ventas', 'verbose_name_plural': 'Ventas'},
        ),
    ]
