# Generated by Django 4.2 on 2025-01-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_ventas_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediosdepago',
            name='imagen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
