# Generated by Django 4.2 on 2025-01-10 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_clientes_apellido_alter_clientes_email_and_more'),
        ('contabilidad', '0006_mediosdepago_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('descripcion', models.TextField(default='', max_length=255)),
                ('precio', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedidoVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientePedido', to='usuarios.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsPEdidoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estadosPEdidoVenta', to='contabilidad.estadopedidoventa')),
            ],
        ),
    ]
